#!bin/bash

curl --request POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/33665856/issues/1/add_spent_time?duration=1h"

# https://gitlab.com/api/v4/projects/33665856/issues/1/add_spent_time?duration=1h
# https://gitlab.com/api/v4/projects/${project}/issues/${issue}/add_spent_time?duration=${spend}h`